import type { HttpDeployManifest } from "../manifest.js";
import { entryPosixPath } from "./entry.js";
import { healthcheckTimeoutText } from "./healthcheck.js";
import type { PackageManagerStrategy } from "./lockfile.js";
import { generatedFileMarkerLine } from "./marker.js";
import type { ProjectPackage } from "./project-package.js";

export interface DeploymentDocInput {
  readonly manifest: HttpDeployManifest;
  readonly packageManager: PackageManagerStrategy;
  readonly project: ProjectPackage;
}

function nameTable(names: readonly string[], group: string): string {
  if (names.length === 0) {
    return `The manifest declares no ${group} variables.`;
  }
  return [
    "| Variable |",
    "| --- |",
    ...names.map((name) => `| \`${name}\` |`),
  ].join("\n");
}

function healthcheckParagraph(manifest: HttpDeployManifest): string {
  const shared = [
    "The generated `deploy/healthcheck.mjs` sends one MCP `initialize` request to",
    `\`http://127.0.0.1:${manifest.image.port}/mcp\` with a ${healthcheckTimeoutText} deadline, one attempt, no retry,`,
    "and no redirect. It exits `0` when the endpoint is healthy and `1` when it is",
    "not, and it prints no header value, response body, or credential.",
    "",
  ];

  if (manifest.healthcheck.expect === "alive") {
    return [
      ...shared,
      "The manifest expectation is `alive`: the endpoint is healthy when it",
      "answers with HTTP 401 carrying a `Bearer` challenge, or with a valid",
      "HTTP 200 `initialize` result. The challenge counts as healthy because it",
      "proves the adapter boundary is serving without the check holding a",
      "credential. HTTP 403, 404, 5xx, a malformed response, a timeout, and a",
      "refused connection are unhealthy.",
    ].join("\n");
  }

  const opening =
    "The manifest expectation is `ready`: only a valid HTTP 200 `initialize` result";
  if (manifest.healthcheck.bearerEnv === undefined) {
    return [
      ...shared,
      opening,
      "is healthy, and HTTP 401 is not. It sends no credential, so the endpoint",
      "must accept an unauthenticated `initialize`.",
    ].join("\n");
  }
  return [
    ...shared,
    opening,
    "is healthy, and HTTP 401 is not. It reads the bearer token from",
    `\`${manifest.healthcheck.bearerEnv}\` and never prints it; the check is unhealthy when`,
    "that variable is unset.",
  ].join("\n");
}

/**
 * Renders the operator documentation from the manifest, so the deployed
 * contract, the generated container, and the health check cannot disagree.
 */
export function renderDeploymentDoc(input: DeploymentDocInput): string {
  const { manifest, packageManager, project } = input;
  const port = manifest.image.port;

  return `${generatedFileMarkerLine("html")}

# Deploying ${project.name}

This file is generated by \`invokta-deploy package\` from
\`invokta.deploy.json\`. Change the manifest and regenerate; a manual edit
blocks regeneration of this file.

The image built from the generated \`Dockerfile\` installs with
\`${packageManager.install}\`, builds with \`${packageManager.build}\`, and runs
\`${entryPosixPath(manifest.entry)}\` as the non-root \`node\` user. It serves MCP Streamable
HTTP on port ${port} at the exact path \`/mcp\`, and terminates plain HTTP only.

## Environment contract

| Variable | Meaning | Default |
| --- | --- | --- |
| \`INVOKTA_HTTP_HOST\` | Bind host passed to \`serveMcpHttp\`; the image sets \`0.0.0.0\`. | \`127.0.0.1\` |
| \`INVOKTA_HTTP_PORT\` | Bind port; when both are set, \`INVOKTA_HTTP_PORT\` wins over \`PORT\`. | \`${port}\` in the image |
| \`PORT\` | Bind port for platforms that inject it. | unset |
| \`INVOKTA_HTTP_ALLOWED_HOSTS\` | Comma-separated \`Host\` allowlist; required for a non-loopback bind. | unset |
| \`INVOKTA_HTTP_ALLOWED_ORIGINS\` | Comma-separated browser origin allowlist. | unset |
| \`INVOKTA_HTTP_MAX_BODY_BYTES\` | Request body limit override. | adapter default (1 MiB) |

List values are split on commas, trimmed, and emptied of blank items. A
non-integer value, an out-of-range value, or a NUL aborts startup instead of
falling back to a default.

## Declared variables

These are the names the manifest declares. Inject their values through the
platform; the toolkit never stores, reads, or generates a value.

### Required

${nameTable(manifest.env.required, "required")}

### Optional

${nameTable(manifest.env.optional, "optional")}

## Health check

${healthcheckParagraph(manifest)}

Because the adapter validates the raw \`Host\` header, the check sends the first
entry of \`INVOKTA_HTTP_ALLOWED_HOSTS\` as its \`Host\` when that variable is
set, so the allowlist never has to admit a loopback host.

## OAuth verification levels

The health check above proves liveness or credential-bearing readiness with one
MCP request. For an OAuth-protected public endpoint, run
\`invokta-deploy inspect-oauth --url https://your-host.example/mcp\` separately.
That read-only command verifies the Bearer challenge, Protected Resource
Metadata, Authorization Server discovery, Authorization Code with S256 PKCE,
advertised client-registration mechanisms, and an advertised JWKS. It does not
perform login, consent, or token exchange.

A complete authorization check requires an interactive OAuth client, such as
Invokta devtools. Keep that homologation separate from container health and
discovery readiness because it needs a browser, a user, and token issuance.

## Deployment topology

- The engine terminates HTTP only. Put a TLS-terminating edge (reverse proxy,
  load balancer, or ingress) in front of any non-loopback deployment, and
  publish an HTTPS URL whose path is exactly \`/mcp\`.
- The adapter validates the raw \`Host\` header and ignores forwarded-host
  headers. The edge must forward the original public \`Host\`, and
  \`INVOKTA_HTTP_ALLOWED_HOSTS\` must list every public host it forwards.
- \`INVOKTA_HTTP_ALLOWED_ORIGINS\` is needed only for browser-based clients
  and must list exact origins.
- The profile is stateless: replicas scale horizontally with no sticky
  sessions, shared state, or drain coordination beyond the graceful-shutdown
  grace period.
- A capability authorization failure is an MCP tool error inside HTTP 200. Edge
  monitoring must not treat it as a transport failure.

## Environment files

- \`.env\` at the project root is a local development convenience, never a
  deployment mechanism. The generated \`.dockerignore\` excludes every
  \`.env*\` file, so no image built from this context contains one.
- Precedence is fixed: the process environment, then the environment file, then the defaults.
  A value already present in the real environment is never overridden, not even
  when it is present and empty.
- \`INVOKTA_ENV_FILE\` points the loader at another file; an explicit path
  that is missing or unreadable fails startup instead of degrading silently.
- In production, inject real values through the platform, and never commit
  \`.env\`. The committed artifact is \`.env.example\`, which carries names
  only.
`;
}
