/**
 * The major version of the toolkit that owns the generated files. It is pinned
 * here rather than read from `package.json` so generated bytes stay a pure
 * function of the release, and a test asserts the two never drift apart.
 */
export const deployToolkitMajorVersion = 0;

/**
 * The fixed marker sentence. Only a file whose first line carries it may be
 * overwritten by a later run, so its text is part of the public contract.
 */
export const generatedFileMarkerText = `generated by invokta-deploy v${deployToolkitMajorVersion} — do not edit; edits block regeneration`;

/** `hash` covers Dockerfile and `.dockerignore`, `line` ESM, `html` Markdown. */
export type GeneratedFileCommentStyle = "hash" | "html" | "line";

const markerLines = Object.freeze({
  hash: `# ${generatedFileMarkerText}`,
  html: `<!-- ${generatedFileMarkerText} -->`,
  line: `// ${generatedFileMarkerText}`,
} as const satisfies Readonly<Record<GeneratedFileCommentStyle, string>>);

export function generatedFileMarkerLine(
  style: GeneratedFileCommentStyle,
): string {
  return markerLines[style];
}

/**
 * Reports whether existing content is toolkit-managed. Only the first line is
 * inspected, and a carriage return left by another tool does not hide it.
 */
export function hasGeneratedFileMarker(
  contents: string,
  style: GeneratedFileCommentStyle,
): boolean {
  const end = contents.indexOf("\n");
  const firstLine = end === -1 ? contents : contents.slice(0, end);
  return firstLine.replace(/\r$/u, "") === markerLines[style];
}
