import type { HttpDeployManifest } from "../manifest.js";
import { renderDeploymentDoc } from "./deployment-doc.js";
import { renderDockerfile } from "./dockerfile.js";
import { renderDockerignore } from "./dockerignore.js";
import { renderHealthcheck } from "./healthcheck.js";
import type { PackageManagerStrategy } from "./lockfile.js";
import {
  type GeneratedFileCommentStyle,
  generatedFileMarkerLine,
} from "./marker.js";
import type { ProjectPackage } from "./project-package.js";

export interface GeneratedFile {
  /** Project-relative POSIX path; also the reporting order key. */
  readonly path: string;
  readonly commentStyle: GeneratedFileCommentStyle;
  readonly markerLine: string;
  readonly contents: string;
}

export interface GeneratedPackageInput {
  readonly manifest: HttpDeployManifest;
  readonly packageManager: PackageManagerStrategy;
  readonly project: ProjectPackage;
}

/** Exactly four files, in the lexicographic order they are reported in. */
export const generatedFilePaths: readonly string[] = Object.freeze([
  ".dockerignore",
  "Dockerfile",
  "deploy/DEPLOYMENT.md",
  "deploy/healthcheck.mjs",
]);

/** Compares by code unit, so the order never depends on a locale. */
export function compareGeneratedPaths(left: string, right: string): number {
  if (left === right) return 0;
  return left < right ? -1 : 1;
}

function file(
  path: string,
  commentStyle: GeneratedFileCommentStyle,
  contents: string,
): GeneratedFile {
  return Object.freeze({
    commentStyle,
    contents,
    markerLine: generatedFileMarkerLine(commentStyle),
    path,
  });
}

/**
 * Computes the whole deployment package. The result is a pure function of the
 * manifest, the project manifest fields, the detected package manager, and the
 * toolkit version: no clock, environment, or path of the running machine
 * reaches the generated bytes.
 */
export function planGeneratedFiles(
  input: GeneratedPackageInput,
): readonly GeneratedFile[] {
  const files = [
    file(".dockerignore", "hash", renderDockerignore()),
    file("Dockerfile", "hash", renderDockerfile(input)),
    file("deploy/DEPLOYMENT.md", "html", renderDeploymentDoc(input)),
    file("deploy/healthcheck.mjs", "line", renderHealthcheck(input)),
  ];
  files.sort((left, right) => compareGeneratedPaths(left.path, right.path));
  return Object.freeze(files);
}
