/**
 * The values `invokta-deploy probe` and the generated `deploy/healthcheck.mjs`
 * must agree on, because they implement one semantic contract against the same
 * endpoint. Both read them from here, so no release can ship a probe and a
 * health check that pin different revisions or deadlines.
 *
 * The module holds data only and imports nothing. The generator inlines these
 * values as literals when it renders the script, so the generated file keeps
 * its self-contained, Node-built-ins-only shape.
 */

/** The protocol revision pinned by ADR 0006. */
export const probeProtocolVersion = "2025-11-25";

/** The default total deadline of one probe, in milliseconds. */
export const probeTimeoutDefaultMs = 3_000;

/**
 * The deadline as it appears in generated prose. It is written out rather than
 * formatted, so no locale can change the generated bytes.
 */
export const probeTimeoutText = "3,000 ms";
