/**
 * The generated `src/http-auth.ts`. The hook is exported in `required` mode
 * and the module fails at load until the author implements it, so a scaffolded
 * engine can never start with an unverified boundary. The development opt-out
 * of the adapter is deliberately absent from this template.
 */
export const httpAuthModuleTemplate = `/**
 * Authentication hook for the MCP HTTP composition root.
 *
 * The adapter calls authenticate() for every request that passes the Host and
 * Origin checks. Return the principal the credential proves, or null to answer
 * with an HTTP 401 Bearer challenge. Verify the credential itself here: the
 * engine authorizes a principal, it does not authenticate one.
 *
 * Generated by "invokta-deploy init". This file is yours to edit.
 */
import type { McpHttpAuthOptions } from "@invokta/mcp";

export const httpAuth = {
  mode: "required",
  authenticate(request) {
    const credential = request.headers.get("authorization");
    if (credential === null) return null;

    // Verify the credential in constant time against the secret this engine
    // declares in its deployment manifest, then return its principal, for
    // example { id: "client:reports" }. Never log the header value.
    return null;
  },
} satisfies McpHttpAuthOptions;

// Delete this line once authenticate() verifies a real credential. Until then
// the module fails at load, so the engine cannot serve an unverified request.
throw new Error(
  "Implement authentication before deploying: edit src/http-auth.ts.",
);
`;
